# version: "3.8"
services:
  build:
    build:
      context: .
      dockerfile: .quartz/Dockerfile
    image: quartz_image
    restart: "no"
  build_docs:
    depends_on:
      - build
    volumes:
      - .:/home/node/quartz/content 
      - /tmp/quartz:/tmp/quartz:rw
    image: quartz_image
    command: ["npx", "quartz", "build", "--output", "/tmp/quartz/public"]
  docs:
    depends_on:
      - build
    image: quartz_image
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/quartz/content 
    stdin_open: true
    tty: true
    restart: "no"
    command: ["npx", "quartz", "build", "--serve", "--port", "8080"]